### ISSUE TITLE
Configuration properties sections are case sensitive

### ISSUE THREAD

**Issue by thompson-tomo** [SteeltoeOSS/Steeltoe#1296] opened 2024-05-12 10:16 UTC
## Describe the bug
When i define my app configuration as per https://docs.steeltoe.io/api/v3/discovery/netflix-eureka.html it is not using the values I am supplying via my configuration layer. If i change the sections key to lower case they do correctly resolve.

## Steps to reproduce 

1. Have a configuration provider generate config as per below
`Data.Add("Eureka:Instance:InstanceId", $"192.168.1.1:90");`
2. Run the application register with a eureka instance
3. Observe that the instanceid received is "localhost:{{appName}}:{{port}}"
4. Change configuration key to be 
`Data.Add("eureka:instance:InstanceId", $"192.168.1.1:90");`
6. Observe instanceid is now set correctly

## Expected behavior
The configuration parameters are not case sensitive

## Environment (please complete the following information):
 - Steeltoe Version 3.2.6
 - OS: Windows 
 - .NET Version Net 8

**Comment by bart-vmware** [comment] 2024-05-13 08:44
I suspect there's something wrong with your app configuration layer, or it executes too late. I'm unable to reproduce this against Steeltoe 3.x. I've tried the following:

1. Open https://github.com/SteeltoeOSS/Samples/blob/main/Discovery/src/FortuneTeller.sln, set **Fortune-Teller-Service** as startup project
2. Add the following line to `Program.cs`, between `.AddCloudFoundryConfiguration()` and `.AddAllActuators()`:
   ```c#
   ConfigureAppConfiguration(builder => builder.AddInMemoryCollection(new Dictionary<string, string>
   {
       { "Eureka:Instance:InstanceId", "some" }
   }))
   ```
3. Start Eureka docker container
4. Select the **Fortune-Teller-Service** launch profile, run the project, and navigate to http://localhost:8761/eureka/apps
5. The registered app shows up with Instance ID "some", see below:
   ![image](https://github.com/SteeltoeOSS/Steeltoe/assets/104792814/1b786a73-de55-463a-a6fb-f1c2727fa6d1)

Can you provide reproduction steps, so it can be reproduced and debugged?

**Comment by thompson-tomo** [comment] 2024-05-13 10:12
i know that it is not an issue with config layer ordering as if I change the casing it correctly resolves it. 

Would it be helpful if I make a basic repo branch rather than try an describe it?

**Comment by thompson-tomo** [comment] 2024-05-13 12:19
Sure thing will do that

**Comment by thompson-tomo** [comment] 2024-05-13 22:57
hmm, this is interesting. I have brought across my entire configuration layer and can't reproduce it.  Changing the casing still results in it working. Maybe some serialisation behaviour differs? But will need to look into this further.

**Comment by bart-vmware** [comment] 2024-05-14 06:14
Thanks for investigating. I'm closing this, as it doesn't seem to be a Steeltoe issue. Feel free to open a new issue when you've identified what's going on.

**Closed by bart-vmware** 2024-05-14 06:14 UTC
Labels: Type/bug
