### ISSUE TITLE
Discovery Service doesn't pick up

### ISSUE THREAD

**Issue by pnguyen535** [SteeltoeOSS/Steeltoe#429] opened 2020-09-04 16:52 UTC
Hi,

Recently, we upgraded Discovery Service to "Spring Cloud Service Registry (3.x)". The environment registry changed from "p-service-registry" to "p.service-registry".

I think that is the reason caused the Discovery Service unable to find services.

Thank you

**Comment by TimHess** [comment] 2020-09-08 14:53
Hi @pnguyen535, did you also happen to upgrade to Steeltoe 3.0 recently? This could be a duplicate of #428 if so

The service registry service binding is mapped based on the presence of a tag for Eureka, it shouldn't matter whether it's p-service-registry or p.service-registry.

**Comment by pnguyen535** [comment] 2020-09-08 16:30
Yes, I upgraded to latest steeltoe 3.0. However, PCF also updated the Discovery Service to 3.x which changed the registration key. 
The code below used to work, but now it returns empty:
var discoveredClients = this.discoveryClient.GetInstances(serviceId);
            if (discoveredClients != null && discoveredClients.Any())
            {
                return discoveredClients.FirstOrDefault()?.Uri;
            }Thank you



    On Tuesday, September 8, 2020, 07:53:25 AM PDT, Tim Hess <notifications@github.com> wrote:  
 
 


Hi @pnguyen535, did you also happen to upgrade to Steeltoe 3.0 recently? This could be a duplicate of #428 if so

The service registry service binding is mapped based on the presence of a tag for Eureka, it shouldn't matter whether it's p-service-registry or p.service-registry.

**Comment by TimHess** [comment] 2020-09-08 16:34
Please try adding a reference to the Cloud Foundry connector package:
`<PackageReference Include="Steeltoe.Connector.CloudFoundry" Version="3.0.0" />`

**Comment by pnguyen535** [comment] 2020-09-10 20:24
It's on "3.0.0" package, but still doesn't work.
Thanks    On Tuesday, September 8, 2020, 09:34:59 AM PDT, Tim Hess <notifications@github.com> wrote:  
 
 


Please try adding a reference to the Cloud Foundry connector package:
<PackageReference Include="Steeltoe.Connector.CloudFoundry" Version="3.0.0" />

**Comment by TimHess** [comment] 2020-09-10 20:26
Can you share all of the Steeltoe references this app has?

**Comment by pnguyen535** [comment] 2020-09-10 20:31
<PackageReference Include="Steeltoe.Common.Hosting" Version="3.0.0" />
    <PackageReference Include="Steeltoe.Extensions.Configuration.CloudFoundryCore" Version="3.0.0" />
    <PackageReference Include="Steeltoe.Management.CloudFoundryCore" Version="3.0.0" />
    <PackageReference Include="Steeltoe.Security.Authentication.CloudFoundryCore" Version="3.0.0"/>    <PackageReference Include="Steeltoe.Common.Net" Version="3.0.0" />    <PackageReference Include="MassTransit.RabbitMQ" Version="7.0.3" />
    <PackageReference Include="Steeltoe.Discovery.ClientCore" Version="3.0.0"    <PackageReference Include="Steeltoe.Connector.ConnectorCore" Version="3.0.0" />
    <PackageReference Include="Steeltoe.Connector.CloudFoundry" Version="3.0.0" />
    <PackageReference Include="Steeltoe.Connector.EFCore" Version="3.0.0" />
    On Thursday, September 10, 2020, 01:26:36 PM PDT, Tim Hess <notifications@github.com> wrote:  
 
 


Can you share all of the Steeltoe references this app has?

**Comment by TimHess** [comment] 2020-09-11 18:03
Those references look correct, something else must be wrong. I just pushed the Steeltoe Discovery sample to an environment with Spring Cloud Registry 3.x, confirmed that the bindings are using `p.service-discovery` and (after adding a reference to `Steeltoe.Connector.CloudFoundry` it seems to work fine - could you try deploying the Steeltoe Discovery sample to see if it works for you in your environment?

**Comment by pnguyen535** [comment] 2020-09-11 19:31
Hi Tim,
Where is the sample project that I can push to my environment?
Thanks    On Friday, September 11, 2020, 11:03:41 AM PDT, Tim Hess <notifications@github.com> wrote:  
 
 


Those references look correct, something else must be wrong. I just pushed the Steeltoe Discovery sample to an environment with Spring Cloud Registry 3.x, confirmed that the bindings are using p.service-discovery and (after adding a reference to Steeltoe.Connector.CloudFoundry it seems to work fine - could you try deploying the Steeltoe Discovery sample to see if it works for you in your environment?

**Comment by TimHess** [comment] 2020-09-11 19:36
I updated the samples to have the reference now, so all you should have to do is deploy one or both of these

This service should show up in the registry:
https://github.com/SteeltoeOSS/Samples/tree/master/Discovery/src/Fortune-Teller-Service

If you want to discover it from an app, this is the front end for it:
https://github.com/SteeltoeOSS/Samples/tree/master/Discovery/src/Fortune-Teller-UI

**Comment by pnguyen535** [comment] 2020-09-11 23:06
Solved my problem. I need to include the Eureka package
<PackageReference Include="Steeltoe.Discovery.Eureka" Version="3.0.0" />
Thank you    On Friday, September 11, 2020, 12:36:33 PM PDT, Tim Hess <notifications@github.com> wrote:  
 
 


I updated the samples to have the reference now, so all you should have to do is deploy one or both of these

This service should show up in the registry:
https://github.com/SteeltoeOSS/Samples/tree/master/Discovery/src/Fortune-Teller-Service

If you want to discover it from an app, this is the front end for it:
https://github.com/SteeltoeOSS/Samples/tree/master/Discovery/src/Fortune-Teller-UI

**Closed** 2020-09-24 16:00 UTC
Labels: Connectors, Discovery, bug, investigate
