### ISSUE TITLE
Create a HytrixMetricsPublisher that publishes in prometheus format

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#264] opened 2020-03-23 15:45 UTC
The Hystrix dashboard has been removed from PCF Spring Cloud Services tile. The spring cloud team has moved from hystrix to resilience4j but Steeltoe will remain on Hystrix. This will allow hystrix metrics to be published in a prometheus format.

**Comment by jkonicki** [comment] 2020-05-07 14:41
Closing as duplicate of #134

**Closed by jkonicki** 2020-05-07 14:41 UTC
Labels: 3.x, CircuitBreaker, Management, duplicate, enhancement
