### ISSUE TITLE
Steeltoe.Extensions.Logging.SerilogDynamicLogger not working as expected

### ISSUE THREAD

**Issue by sajanep** [SteeltoeOSS/Steeltoe#113] opened 2019-09-02 11:59 UTC
## Describe the bug
I have a .net core 2.2 application which is deployed in PCF 2.4.12. Configured Serilog and enabled dynamic console to adjust the log levels without restarting the application. But unfortunately the number of loggers appearing PCF Apps Manager is just 1. Upon adjusting the levels, there is no effect.

## Steps to reproduce 
1. Deploy  https://github.com/SteeltoeOSS/Samples/tree/master/Management/src/AspDotNetCore/CloudFoundry after integrating Serilog. 
2. Configure Serilog dynamic console like below
```
public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseCloudFoundryHosting()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .ConfigureAppConfiguration((builderContext, config) =>
                {
                    config.SetBasePath(builderContext.HostingEnvironment.ContentRootPath)
                        .AddCommandLine(args)
                        .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                        .AddJsonFile($"appsettings.{builderContext.HostingEnvironment.EnvironmentName}.json", optional: true)
                        .AddCloudFoundry()
                        .AddEnvironmentVariables();
                })
                .UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration
                     .ReadFrom.Configuration(hostingContext.Configuration)
                     .WriteTo.Trace())
                .ConfigureLogging((builderContext, loggingBuilder) =>
                {
                    loggingBuilder.AddConfiguration(builderContext.Configuration.GetSection("Logging"));
                    loggingBuilder.AddDebug();
                    // Add Serilog Dynamic Logger 
                    loggingBuilder.AddSerilogDynamicConsole();
                })
                .Build();

            host.RunWithTasks();
```

## Expected behavior
Number of loggers appearing in PCF Apps Manager should be matching the typed ILogger<T> used in the application and upon the adjusting the log levels, log statements should appear accordingly. 

## Environment (please complete the following information):
 - Platform: PCF 2.4.12 
 - OS:  Linux
 - .NET Version : .net core 2.2
 - Steeltoe Version:  2.3.0
 - Any other library versions to note

**Comment by hananiel** [comment] 2019-09-09 15:27
hey @sajanep I saw your response on SO. I will take a look. github.com/SteeltoeOSS/Samples/tree/master/Management/src/… with the changes mentioned in Program.cs above and put the Serilog configuration in appsettings.json like mentioned in my first post. Btw, is there any good example demonstrating the usage of steeltoe.io/docs/steeltoe-logging/#2-0-serilog-dynamic-logger.

**Comment by sajanep** [comment] 2019-10-28 12:39
> I investigated and found this: There are two things we are talking about ... what shows up by default in the Loggers view, and what is there but hidden until you search. The Cloudfoundry apps manager UI, only shows the "Configured" settings in this view. You can still see the other loggers by typing and searching in the filter. The number of Configured settings corresponds to the Overrides below. The default will always be there ...
> 
> ```
> "Serilog": {
>       "MinimumLevel": {
>         "Default": "Information",
>         "Override": {
>           "Microsoft": "Warning",
>           "CloudFoundry.Controllers": "Verbose"
>         }
>       },
> ```
> 
> As expected, the number of loggers matches the typed ILogger. But you have to set an override to see the default view.
> Second, there is a difference between the granularity of control for Serilog vs the normal dynamic logger. In the Steeltoe dynamic logger, you can filter at any level. For namespace A.B.C.D you can filter at any level. In Serilog to filter by A.B._, you have to provide an override for A.B. And then any setting you apply to a child will set the level for the Override. In other words, setting A.B.C to Debug will set . A.B._ to Debug. While not ideal, given the level of exposed interfaces from Serilog that is the best we could do at this time. Closing this for now.

I am bit confused here. So are you saying the number of loggers under "Filter Loggers" is equal to the number of overrides. I tried this, but sill I am not getting anything other than "Default"(I typed in too with the namespace I entered under overrides). Not sure what is wrong with my setup. Also adjusting Default logger does not have any effect(it's not getting applied)

**Comment by hananiel** [comment] 2019-10-28 12:46
Have you removed the UseSerilog?  I would suggest getting the sample here, push to cloud foundry without any changes and see If it works: https://github.com/SteeltoeOSS/Samples/tree/2.x/Management/src/AspDotNetCore/CloudFoundry

**Comment by sajanep** [comment] 2019-10-28 12:55
> Have you removed the UseSerilog? I would suggest getting the sample here, push to cloud foundry without any changes and see If it works: https://github.com/SteeltoeOSS/Samples/tree/2.x/Management/src/AspDotNetCore/CloudFoundry

Nope, I have still UseSerilog. Will it create any issue? My Program.cs is like below

```
public class Program
    {
        /// <summary>
        /// Main 
        /// </summary>
        /// <param name="args"></param>
        /// <returns></returns>
        public static async Task Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        /// <summary>
        /// CreateWebHostBuilder
        /// </summary>
        /// <param name="args"></param>
        /// <returns></returns>
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureAppConfiguration((hostContext, configApp) =>
                {
                    configApp.AddCloudFoundry();
                    configApp.AddConfigServer();
                })
                .UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration
                     .ReadFrom.Configuration(hostingContext.Configuration))
                .ConfigureLogging((builderContext, loggingBuilder) =>
                 {
                     loggingBuilder.ClearProviders();
                     // Add Serilog Dynamic Logger 
                     loggingBuilder.AddSerilogDynamicConsole();
                 });
    }
}
```

**Comment by hananiel** [comment] 2019-10-28 13:05
I don’t think that will work.

**Comment by sajanep** [comment] 2019-10-31 08:12
Hello, I pulled down the mentioned sample and deployed to my PCF instance. I commented out few things like MySQLDbContext and tasks etc(Since I don't have any MySQL instance). After this I was able to see loggers in PCF Apps Manager. But please note that till this time, no integration with Serilog happended. So I pulled down below packages to integrate Serilog
```
 <PackageReference Include="Serilog.AspNetCore" Version="3.1.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Trace" Version="2.1.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="1.1.0" />
```
So after this my Program.cs looks like below
 ```
public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseCloudFoundryHosting()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .ConfigureAppConfiguration((builderContext, config) =>
                {
                    config.SetBasePath(builderContext.HostingEnvironment.ContentRootPath)
                        .AddCommandLine(args)
                        .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                        .AddJsonFile($"appsettings.{builderContext.HostingEnvironment.EnvironmentName}.json", optional: true)
                        .AddCloudFoundry()
                        .AddEnvironmentVariables();
                })
                 .UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration
                     .ReadFrom.Configuration(hostingContext.Configuration))
                .ConfigureLogging((builderContext, loggingBuilder) =>
                {
                    loggingBuilder.AddConfiguration(builderContext.Configuration.GetSection("Logging"));
                    // loggingBuilder.AddDynamicConsole();
                    loggingBuilder.AddSerilogDynamicConsole();
                    loggingBuilder.AddDebug();
                })
                .Build();

            //host.RunWithTasks();
            host.Run();
        }
```
After re-deploying(publish and cf push), PCF Apps Manager only showing Default(I typed in too), and also adjusting the levels is not getting into effect. Btw do you have any simple which works with complete serilog integration(Not just the serilog dynamic console integration)

**Comment by sajanep** [comment] 2019-11-05 09:01
Hello,
Sorry I was not aware about this. I removed UseSerilog() and other Serilog dependencies. I am able to see loggers now. I do have a follow up question regarding below lines

```
 .ConfigureLogging((builderContext, loggingBuilder) =>
               {
                   loggingBuilder.AddConfiguration(builderContext.Configuration.GetSection("Logging"));
                   // loggingBuilder.AddDynamicConsole();
                   loggingBuilder.AddSerilogDynamicConsole();
                   loggingBuilder.AddDebug();
               })
```
Do we really need  loggingBuilder.AddConfiguration(builderContext.Configuration.GetSection("Logging")) and how about Logging section in appSettings.json, since Serilog already has this section

**Comment by hananiel** [comment] 2019-11-05 15:04
> Do we really need loggingBuilder.AddConfiguration(builderContext.Configuration.GetSection("Logging")) and how about Logging section in appSettings.json, since Serilog already have this section?

No we do not. I did not want to make two different samples since they are so similar - but yes that line can be commented out. You only need that for the "AddDynamicConsole"

**Comment by hananiel** [comment] 2019-11-06 04:51
@sajanep closing this issue for now. feel free to reopen. Also the 2.4.0-rc1 release has some enhancements and bug fixes - make sure you test with the updated nugets.

**Comment by ani00763** [comment] 2020-08-06 22:21
I have an application where I'm trying to implement Steeltoe dynamic serilogger, but its not working. I followed following steps, could you please help me figuring out what I'm doing wrong. Sorry for long post, but i wanted to explain all possible scenarios I have tried. I found this thread as closed but still not able to make it work at my end.

1) Create new .Net Core API project.
2) Added below nuget packages
![image](https://user-images.githubusercontent.com/69315451/89586541-7fdf5400-d805-11ea-93f8-38cbc3f9b3ad.png)

3) Program.cs looks like,
![image](https://user-images.githubusercontent.com/69315451/89586634-b6b56a00-d805-11ea-9376-f5bc878aa1e4.png)

4) appsettings.json looks like,
![image](https://user-images.githubusercontent.com/69315451/89587607-8c64ac00-d807-11ea-988e-66da2d69b93c.png)

5) Controller looks like,
![image](https://user-images.githubusercontent.com/69315451/89587064-71456c80-d806-11ea-8c5e-323e8758f9de.png)
 
**Scenario 1**:
When I comment below lines from Program.cs,
![image](https://user-images.githubusercontent.com/69315451/89587180-b7023500-d806-11ea-9144-3b1ab93342b8.png)

I get below logs, so assuming its referring some default verbosity levels and not referring to appsettings,
![image](https://user-images.githubusercontent.com/69315451/89587238-d7ca8a80-d806-11ea-8f3a-afcd096a48d8.png)

**Scenario 2**:
When I uncomment above lines, and comment the Serilog section in appsettings, it refers the Logging section in appsettings and log below lines as expected,
![image](https://user-images.githubusercontent.com/69315451/89587372-1e1fe980-d807-11ea-986e-6fe2c969abcf.png)

**Scenario 3**:
When I uncomment Serilog section in appsettings and have both Logging and Serilog Sections, application logs same line twice like below,
![image](https://user-images.githubusercontent.com/69315451/89587565-7a830900-d807-11ea-900a-41252750778c.png)

**Scenario 4**:
When I comment Logging section in appsettings and keep only Serilog Section, application still logs same line twice but skips the verbose/trace log,
![image](https://user-images.githubusercontent.com/69315451/89587815-fb420500-d807-11ea-9c33-6596f6b5a7ba.png)

And in all scenarios the dynamic logging wont work after pushing app to cloud foundry. Your help is much appreciated.

**Comment by jkonicki** [comment] 2020-08-06 23:03
@hananiel Are you able to look at this?

**Comment by ani00763** [comment] 2020-08-13 14:14
Did  anyone got chance to look into this? I'm still looking for some help here. 

Thank you,

**Comment by hananiel** [comment] 2020-08-13 18:36
@ani00763  I am looking at it now ...

**Comment by tomer-cohen** [comment] 2020-08-17 14:00
@hananiel  , is it possible to use the AddSerilogDynamicLogger() without removing UseSerilog() ? I'm using SerilogRequestLogging which demands it.

**Comment by ani00763** [comment] 2020-08-17 19:33
@hananiel Thank you for looking into the issue. I'll work on the suggestion and also refer the app you pushed and will let you know.  Also when i said Dynamic logging is not working, i meant to say logging was working but the changing the logs levels was not having any effect.
Also looks like the SerilogDynamicLoggerCore nuget don't have support to async console logging of serilog. it would be great if you can add the async console serilog dependency with it.

Thank you!

**Comment by ani00763** [comment] 2020-08-17 21:27
@hananiel When i change the log levels after deploying my app to cloudfoundry it not working. Attaching my code here. Could you please verify what i'm doing wrong.
[DynamicSeriloggerTestingAPI.zip](https://github.com/SteeltoeOSS/Steeltoe/files/5086875/DynamicSeriloggerTestingAPI.zip)

**Comment by ani00763** [comment] 2020-08-24 14:06
@hananiel did you get chance to look into the test project i shared? I tried all your suggestions and still not able to make the Dynamic logging work in cloudfoundary.

**Comment by hananiel** [comment] 2020-09-09 15:43
@ani00763, I did download and push this to cloud foundry and it works fine for me.  Make sure you are adjusting log levels for the correct namespace. For this sample you posted: search for DynamicSerilogTestingApi and adjust the controller log levels. In my case, I changed it from Trace to Error and then can only see error logs. 
![image](https://user-images.githubusercontent.com/887691/92621226-9019a180-f291-11ea-8bac-0b14985ddc0a.png)

**Comment by ani00763** [comment] 2020-09-09 16:06
@hananiel  Thank you very much, I was trying to adjust the log levels for Default that's why it was not working for me. After filtering it on DynamicSeriloggerTestingAPI it started working. Only problem i see now is when i set it to Trace, its not showing the trace log all other levels are working fine.

**Comment by hananiel** [comment] 2020-09-09 16:21
@ani00763 yes, I can confirm this sample is having that issue both locally and on cf. let me investigate and get back.

**Comment by hananiel** [comment] 2020-09-09 16:24
> @hananiel , is it possible to use the AddSerilogDynamicLogger() without removing UseSerilog() ? I'm using SerilogRequestLogging which demands it.

@tomer-cohen unfortunately Serilog uses the Serilog.ILogger and DynamicLogging is built on Microsoft ILogger. So the only recourse is to copy the HttprequestMiddle ware and replace Log.ForContext<> with Microsoft.ILogger. I don't know how configuration and other things will work together - I haven't done it.

**Comment by ani00763** [comment] 2020-09-09 16:58
@hananiel the debug and trace level works if we add Logging section,
"Logging": {
    "LogLevel": {
      "Default": "Trace",
      "Microsoft": "Warning",
      "Steeltoe": "Warning"
    }
  }

**Comment by hananiel** [comment] 2020-09-09 17:50
> @hananiel the debug and trace level works if we add Logging section,
I was just going to tell you this - glad you figured out. I am going close this issue. Feel free to open a new issue if you have more issues to resolve.

**Closed by hananiel** 2020-09-09 17:50 UTC
Labels: 2.x, Logging, bug
