### ISSUE TITLE
Dynamic Serilog: Unable to increase log level beyond Default

### ISSUE THREAD

**Issue by jeremyhayes** [SteeltoeOSS/Steeltoe#685] opened 2021-06-07 15:55 UTC
## Describe the bug
When using Serilog dynamic logging integration, unable to increase logging verbosity beyond `Default` logger level in app configuration.

## Steps to reproduce 
1. Configure Dynamic Serilog
2. Configure Loggers actuator
3. Set `Default` logger at "Information" level
4. Invoke logger for each level 
  a. should log at Info/Warn/Error/Critical
5. Invoke `POST` loggers actuator to change `Default` logger to "Trace" level. 
  a. Confirm `effectiveLevel` via `GET` loggers actuator.
6. Invoke logger for each level
  a. Expected: should log at all levels
  b. Actual: still only logs at Info/Warn/Error/Critical

## Expected behavior
Should be able to run application with `Default` logger level at "Information", then dynamically increase logging verbosity at runtime for issue investigation.

## Environment (please complete the following information):
 - Steeltoe Version: 2.4.5 / 3.0.2 / 3.1.0-rc1
 - Platform: local development environment
 - OS: Windows
 - .NET Version: net5.0
 - Any other library versions to note
   - Serilog Version: transitive (no direct dependencies)

## Additional context or links

Here is a minimal example. Invoking the scaffolded `GET /weatherforecast` endpoint will call the logger for each available level. The loggers actuator is at `/actuator/loggers`. There are a few branches testing various workarounds.
* https://github.com/jeremyhayes/steeltoe-dynamic-serilog-example

As a workaround, you can set the `Default` logger to `"Trace"` level. It is important to note that this must be done via the _Microsoft_ logger config, regardless of _Serilog's_ configuration. The tradeoff here is that you must now provide overrides for any/all categories which shouldn't use Verbose logging, which can be unwieldy depending on included packages.

This does not affect the non-Serilog `DynamicConsoleLogger`.

I suspect this is an issue with Serilog's `LoggingLevelSwitch`, but I'm not sure if it's due to Steeltoe's usage, or in Serilog itself. Figured I'd start here. :)

**Comment by hananiel** [comment] 2021-06-10 19:17
@jeremyhayes  Thanks for the issue.  I can confirm there is an issue - with Steeltoe's use of Serilog. After a brief investigation, I realize that a lot of confusion has to do with the default Microsoft providers (console, debug etc).. When you 'UseSerilog' it replaces the ILoggingFactory with the `SerilogLoggerFactory` and does not have some of these issues.    However when you use the `DynamicConsoleLoggerProvider` or the `SerilogDynamicProvider` we keep the Microsoft default ILoggingFactory. So there is an additional level of filtering that is happening. As you noted, adding the following helps you see `Debug` and below, but not `Trace` level. However it should allow you to still dynamically filter between these lower levels i.e. Debug or Info to Critical. 
```json
  "Logging": {
    "LogLevel": {
      "Default": "Trace",
```
This mismatch was a regression that crept in since the original implementation and we have to fix it and is in the backlog and will be fixed. I believe we need to wrap SerilogLoggerFactory and proxy the CreateLogger to the IDynamicLoggerProvider - in theory that should solve this problem.

**Closed** 2021-09-07 15:27 UTC
Labels: Type/bug, help wanted, ReleaseLine/3.x, Component/Logging, ReleaseLine/2.x
