### ISSUE TITLE
Running with Consul Throws CheckID does not have associated TTL

### ISSUE THREAD

**Issue by sorvis** [SteeltoeOSS/Steeltoe#14] opened 2019-04-26 19:09 UTC
Hello,

I'm testing out discovery with Consul. I have setup my application like this:

Nuget:
```
<PackageReference Include="Steeltoe.Discovery.ClientCore" Version="2.2.0" />
<PackageReference Include="Steeltoe.Management.CloudFoundry" Version="1.1.0" />
```

Startup.cs
```
public void ConfigureApplication(IApplicationBuilder app, IHostingEnvironment env, IApplicationLifetime applicationLifetime)
{
    app.UseDiscoveryClient();
}

public void ConfigureServices(IServiceCollection services, IConfigurationRoot config)
{
    services.AddDiscoveryClient(config);
}
```

appsettings.json
```
"consul": {
    "host": "localhost",
    "ttl":  "5",
    "discovery": {
      "serviceName": "Test",
      "healthCheckUrl": "/health",
      "heartbeat:enabled": true,
      "heartbeat:ttlValue": "5"
    }
  },
```

Started docker instance of consul with:
```
docker run -p 8500:8500 -d --name=dev-consul consul
```

Then when I start my application I get this error message:

> Consul.ConsulRequestException
>   HResult=0x80131500
>   Message=Unexpected response, status code InternalServerError: CheckID "service:Test-1128208441" does not have associated TTL
>   Source=Consul
>   StackTrace:
>    at Consul.PutNothingRequest.<Execute>d__5.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Steeltoe.Discovery.Consul.Discovery.TtlScheduler.<<Add>b__11_0>d.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> 

Am I missing some configuration?

**Comment by dtillman** [comment] 2020-03-23 14:29
Seems like maybe the configuration you tried was not in proper format maybe? .. and so the consul config was not being detected?

**Comment by gpltaylor** [comment] 2020-04-12 16:18
I have the same issue. Is there a patch for this. AKA downgrading or something.
Also, the link to PT is "not found".

**Comment by jkonicki** [comment] 2020-04-13 13:20
@gpltaylor We no longer use Pivotal tracker, so I have removed the comments for that.  
@dtillman Any more help you can provide here?

**Comment by dtillman** [comment] 2020-04-13 15:17
@gpltaylor : Can you try setting the config values I mentioned above, to see if it works?
I think the previous issue reporter might have not correctly entered the JSON into his AppSettings ..
If it doesn't solve it.. any chance you have a sample?
Dave

**Comment by gpltaylor** [comment] 2020-04-15 10:09
@dtillman yes this works (when I type it correctly :) )
thanx

**Comment by TimHess** [comment] 2020-06-16 19:08
This issue appears to have been caused by application configuration issues and there doesn't appear to be a problem with Steeltoe. I'm going to close the issue, but please re-open if needed

**Closed by TimHess** 2020-06-16 19:08 UTC
Labels: Discovery, question
