### ISSUE TITLE
TraceDiagnosticObserver: Random Null Reference Exception

### ISSUE THREAD

**Issue by Sudhakar85** [SteeltoeOSS/Steeltoe#432] opened 2020-09-10 21:16 UTC
## Describe the bug
We are randomly getting object reference exception from TraceDiagnosticObserver

## Steps to reproduce 
Not able to reproduce this issue and it's happening randomly

## Expected behavior
Null Check should be added to handle this scenario

## Environment (please complete the following information):
 - Platform: PCF
 - OS: Linux
 - .NET Core 3.1.0,
 - Steeltoe Version 2.4.3

## Exception

![image](https://user-images.githubusercontent.com/11510071/93040179-fb0b0580-f60e-11ea-8b38-9a5a6c16026b.png)

**Comment by vivekkjain** [comment] 2020-09-13 03:59
Could you please prioritize this?

**Comment by hananiel** [comment] 2020-09-14 14:33
Not exactly sure why this is happening, but seems similar to https://github.com/dotnet/aspnetcore/issues/3219. Since we don't what other middleware are configured etc, I am adding a try/catch for these to log an error message and move on.

**Comment by hananiel** [comment] 2020-09-14 15:42
@vivekkjain @Sudhakar85  can you share the project dependencies and even startup / program for this or better a full project that can reproduce this. How random is it. Does it happen only at startup or at other times in the lifecycle of the app.

**Comment by vivekkjain** [comment] 2020-09-14 19:29
@hananiel  this is happening frequently and not limited to startup. As this might be due to health check. We have this application vmware tanzu where the instance are randomly crashing and restarting.

**Comment by Sudhakar85** [comment] 2020-09-14 20:25
**Program.cs** 
`
public static class Program
{
        public static void Main(string[] args)
        {
            try
            {
                WebHostDefaultBuilder.CreateWebHostBuilder(args)
                    .UseStartup<Startup>()
                    .ConfigureAppConfiguration((context, builder) =>
                    {
                        builder.AddConfigServer(context.HostingEnvironment.EnvironmentName, "XXXXXX");
                    })
                    .Build()
                    .Run();
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host Quit Unexpectedly");
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }
}

**Startup.cs** 

[ExcludeFromCodeCoverage]
public class Startup
{
	public Startup(IConfiguration configuration)
	{
		Configuration = configuration;
	}

	public IConfiguration Configuration { get; }

	public void ConfigureServices(IServiceCollection services)
	{
		services.AddApiVersioning(options => options.AssumeDefaultVersionWhenUnspecified = true);
		services.Configure<CookiePolicyOptions>(options =>
		{
			// This lambda determines whether user consent for non-essential cookies is needed for a given request.
			options.CheckConsentNeeded = context => true;
			options.MinimumSameSitePolicy = SameSiteMode.None;
		});

		services.AddMvc(options =>
						{
							options.Filters.Add(new MiddlewareFilterAttribute(typeof(LocalizationPipeline)));
							options.Filters.Add(new MiddlewareFilterAttribute(typeof(ComponentConfigurationPipeline)));
							options.Filters.Add(new HttpResponseExceptionFilter());
						})
			.SetCompatibilityVersion(CompatibilityVersion.Version_3_0)
			.AddFeatureFolders();
		
		services.AddMemoryCache();

	}

	public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
	{            
		app.UseStaticFiles();

		if (env.IsDevelopment())
		{
			app.UseDeveloperExceptionPage();
		}
		else
		{
			app.UseMiddleware<ErrorHandlerMiddleware>();
		}
		app.UseHsts();

		if (env.IsStaging() || env.IsProduction())
				app.UseHttpsRedirection();

		app.UseRouting();
		
		app.UseCookiePolicy();            
		app.UseEndpoints(endpoint => 
		{
			endpoint.MapDefaultControllerRoute();
		});

		if (!env.IsDevelopment())
		{
			app.UseCloudFoundryActuators();
		}

		app.UseBrowserLink();
		
	}        
}

`

**Comment by hananiel** [comment] 2020-09-17 14:48
@Sudhakar85 this Startup.cs doesn't look right to me. Any UseCloudFoundryActuators must be preceded by AddCloudFoundryActuators.  Can you checkin a complete project somewhere or attach a zip file?

**Comment by Sudhakar85** [comment] 2020-09-18 14:00
@hananiel , sorry i can't share entire code, yes i do have AddCloudFoundryActuators but not AddDistrubutedTracing.

**Comment by Sudhakar85** [comment] 2020-09-18 14:05
@hananiel , as highlighted below, i can see the TraceDiagnosticObserver is registered inside AddCloudFoundryActuators 

![image](https://user-images.githubusercontent.com/11510071/93606632-eff90200-f98d-11ea-8818-6b17b2e70b64.png)

**Comment by hananiel** [comment] 2020-09-18 14:08
@Sudhakar85 Ok makes sense. Can you do me a favor and run this sample: https://github.com/SteeltoeOSS/Samples/tree/2.x/Management/src/AspDotNetCore/Tracing and see if you are getting the same error? 
If you want you can comment out the addDistributedTracing ( which is only needed if you want traces exported to Zipkin).

**Comment by hananiel** [comment] 2020-09-18 14:16
@Sudhakar85  can you come on steeltoe slack and we can walk through this? steeltoeteam.slack.com

**Comment by hananiel** [comment] 2020-09-25 00:23
@Sudhakar85 After looking into this further, https://github.com/dotnet/aspnetcore/issues/11069  is another example of this sort of issue. The main thing seems to be multiple threads accessing the httpContext. The pattern we are using with DiagnosticListener in Steeltoe is a well-documented and widely used pattern and I don't see any other issues with the code. So I am suspecting some other element of the application code causing this issue. So unless we can have a reproduction project, we cannot troubleshoot anymore. So I am closing this ticket for now. Feel free to reopen with a small reproduction project if needed.

**Closed by hananiel** 2020-09-25 00:23 UTC
Labels: 2.x, 3.x, Management, bug
