### ISSUE TITLE
Consider making the heap dump collection logic work on Linux for .NET Core 3

### ISSUE THREAD

**Issue by cshung** [SteeltoeOSS/steeltoe#44] opened 2019-05-30 06:56 UTC
In .NET Core 3, it is possible to collect a heap dump of a process running on Linux using [`Microsoft.Diagnostics.Tools.RuntimeClient.GenerateCoreDump`](https://github.com/dotnet/diagnostics/blob/03c882f585f599df1a419f00ad3bdfc29e87a116/src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticHelpers.cs#L34).

**Comment by jkonicki** [comment] 2019-10-04 20:33
Duplicate of #100

**Closed by jkonicki** 2019-10-04 20:33 UTC
Labels: Management, duplicate, enhancement, help wanted
